### ISSUE TITLE
Rename packages or use old package names

### ISSUE THREAD

**Issue by adrianhopebailie** [adrianhopebailie/interledgerjs#3]
This proposal uses new package names for the packages putting them under the `@interledger` scope.

The motivation is to explicitly mark these as new packages so that users will explicitly migrate from the old packages to these.

This allows us to drop a number of hacks that are present in existing modules that try to get around different module system inconsistencies, and were needed to ensure backward compatibility with previous JS implementations.

Let's not do this anymore:

```
const createLogger = function (namespace: string) {
  return new Logger(namespace)
} as ModuleExport

interface ModuleExport {
  (namespace: string): Logger
  default: ModuleExport
  Logger: Function
}

createLogger.default = createLogger
createLogger.Logger = Logger
export default createLogger

module.exports = createLogger
```

or the `reader.js`, `writer.js` etc files needed in the root of the [oer-utils](https://github.com/interledgerjs/oer-utils) module.

**Comment by sublimator** [comment]
Use named exports and ban default exports ?
That would imply more care taken when moving to the new packages huh ?
I guess if you're going to break things/clean up, now is the time ?

**Comment by adrianhopebailie** [comment]
> Use named exports and ban default exports ?
> That would imply more care taken when moving to the new packages huh ?
> I guess if you're going to break things/clean up, now is the time ?
Yes yes and yes.

After chatting with @sharafian , @matdehaast and @donchangfoot we decided to keep the package names the same but do a major version update.

This means there is less change to be reviewed but it also signals to users that their MAY be breaking changes for them

**Comment by kincaidoneil** [comment]
@sublimator has a good point, a lot of the inconsistencies between CJS/AMD/UMD would be mitigated if we only used named exports ([among other reasons against default exports](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad)).

(Also, ES modules are likely [going to be supported](https://blog.logrocket.com/es-modules-in-node-js-12-from-experimental-to-release/) by default in Node.js 12 when it goes into LTS later this year. Fingers crossed, _eventually_, this may solve some of these issues!)
